targets:
  $default:
    sources:
      - $package$
      - lib/**
      - pubspec.yaml
      - test/**
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/**
            - test/**
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
          #nullable: true
      freezed:
        enabled: true
        options:
          union_key: type
          union_value_case: snake
        generate_for:
          include:
            - lib/**
            - test/**
      #built_value_generator|built_value:
      #  enabled: true
      #  generate_for:
      #    exclude:
      #      - test
      #    include:
      #      - lib/**
      build_web_compilers:entrypoint:
        # These are globs for the entrypoints you want to compile.
        generate_for:
          - test/**.browser_test.dart
          - web/**.dart
        enabled: true
        options:
          sound_null_safety: true
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
            - -DIS_WEB=true
            - -O2
      pubspec_generator:
        options:
          output: lib/src/common/constant/pubspec.yaml.g.dart
