name: dart_jobs_client
description: Dart Jobs
publish_to: 'none'
version: 0.1.0+1634411913

environment:
  sdk: ">=2.15.0-178.1.beta"
  flutter: ">=2.7.0-3.1.pre"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Localization
  intl: ^0.17.0

  # Annotation & Code-generation
  meta: ^1.7.0
  #built_value: ^8.1.2
  json_annotation: ^4.3.0
  freezed_annotation: ^1.0.0
  #protobuf: ^2.0.0

  # State manager & Inversion of Control
  #fox_flutter_bloc: ^0.1.0
  flutter_bloc: ^8.0.0
  bloc_concurrency: ^0.2.0

  # Network
  #grpc: ^3.0.2
  dio: ^4.0.1
  #retrofit: ^2.2.0

  # Storage and SQL
  shared_preferences: ^2.0.5

  # Firebase
  firebase_core: ^1.1.1
  firebase_analytics: ^9.0.3
  firebase_auth: ^3.1.0
  cloud_firestore: ^3.1.1
  firebase_crashlytics: ^2.0.3
  firebase_performance: ^0.8.0+2
  firebase_remote_config: ^1.0.0-dev.3
  #firebase_messaging: ^10.0.8

  # Utility & Helpers
  platform_info: ^3.1.0
  l: ^3.0.1
  url_launcher: ^6.0.3
  path_provider: ^2.0.2
  path: ^1.7.0
  multiline: ^3.0.0
  #geolocator: ^7.0.3
  #permission_handler: ^8.0.0+2
  async: ^2.6.1
  collection: ^1.15.0
  #money2: ^3.0.0-beta.6
  fixnum: ^1.0.0
  dart_jobs_shared:
    path: ../shared

  # Transformers
  rxdart: ^0.27.0

  # Authentication
  sign_button: ^2.0.0 # Кнопки аутентификации
  google_sign_in: ^5.0.3

  # UI & Widgets
  shimmer: ^2.0.0
  #google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #integration_test:
  #  sdk: flutter
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  mockito: ^5.0.15
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.5.0
  #built_value_generator: ^8.1.2
  flutter_launcher_icons: ^0.9.0
  json_serializable: ^6.0.1
  freezed: ^1.0.0
  #retrofit_generator: ^2.2.0
  pubspec_generator: ^3.0.1
  flutter_gen_runner: ^4.0.1
  args: ^2.0.0
  #pigeon: ^0.3.0

dependency_overrides:
  #analyzer: ^2.7.0
  gql_exec: 0.3.0 # https://github.com/gql-dart/gql/issues/289

# Flutter assets and config
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image/dart_logo/

# Flutter assets codegen
flutter_gen:
  output: lib/src/common/constant/
  line_length: 120

# Generate app icon
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/icon/1x/icon.png"
  image_path_android: "assets/icon/1x/icon.png"
  image_path_ios: "assets/icon/1x/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/icons/background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/icons/foreground.png" # only available for Android 8.0 devices and above


flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: Localized # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/src/common/localization # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/src/common/localization # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
