name: dart_jobs_client
description: Dart Jobs
publish_to: 'none'
version: 0.6.0+1648943120

environment:
  sdk: '>=2.16.0'
  flutter: '>=2.10.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Localization
  intl: ^0.17.0

  # Annotation & Code-generation
  meta: ^1.7.0
  json_annotation: ^4.3.0
  freezed_annotation: ^1.0.0

  # State manager & Inversion of Control
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0

  # Storage and SQL
  shared_preferences: ^2.0.13

  # Firebase
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.10
  cloud_firestore: ^3.1.11
  firebase_crashlytics: ^2.5.3
  firebase_performance: ^0.8.0+8
  firebase_remote_config: ^2.0.2
  firebase_messaging: ^11.2.10
  firebase_dynamic_links: ^4.1.0

  # Utility & Helpers
  #connectivity_plus: 2.2.0
  share_plus: ^4.0.3
  stack_trace: ^1.10.0
  sentry_flutter: ^6.4.0
  sentry: ^6.4.0
  platform_info: ^3.1.0
  platform_detect: ^2.0.3
  l: ^3.1.0
  url_launcher: ^6.0.20
  path_provider: ^2.0.9
  path: ^1.8.0
  #multiline: 3.0.0
  #geolocator: 7.0.3
  #permission_handler: 8.0.0+2
  async: ^2.8.2
  collection: ^1.15.0
  #money2: 3.0.0-beta.6
  fixnum: ^1.0.0
  dart_jobs_shared:
    path: ../shared

  # Transformers
  rxdart: ^0.27.3

  # Authentication
  google_sign_in: ^5.2.4

  # UI & Widgets
  #google_fonts: 2.1.0
  #flutterfire_ui: 0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #integration_test:
  #  sdk: flutter
  analyzer: ">=2.8.0 <4.0.0"
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  mockito: ^5.0.15
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.12.0
  #built_value_generator: ^8.1.2
  json_serializable: ^6.0.1
  freezed: ^1.1.0
  #retrofit_generator: ^2.2.0
  pubspec_generator: ^3.0.1
  flutter_gen_runner: ^4.0.1
  args: ^2.0.0
  #pigeon: ^0.3.0
  pub_semver: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.1+1

#dependency_overrides:
  #analyzer: ^2.7.0
  # https://github.com/gql-dart/gql/issues/289
  #gql_exec: 0.3.0

# Flutter assets and config
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image/dart_logo/

# Flutter assets codegen
flutter_gen:
  output: lib/src/common/constant/
  line_length: 120

# Generate app icon
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/icon/1x/icon.png"
  image_path_android: "assets/icon/1x/icon.png"
  image_path_ios: "assets/icon/1x/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/icons/background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/icons/foreground.png" # only available for Android 8.0 devices and above

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#cfd8dc"
  #background_image: "assets/background.png"

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/splash/image.png

flutter_intl:
  # Required. Must be set to true to activate the plugin.
  enabled: true # Default: false
  # Optional. Sets the name for the generated localization class.
  class_name: Localized # Default: S
  # Optional. Sets the main locale used for generating localization files.
  # Provided value should consist of language code and optional script and country codes
  # separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN').
  main_locale: en # Default: en
  # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system.
  arb_dir: lib/src/common/localization # Default: lib/l10n
  # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system.
  output_dir: lib/src/common/localization # Default: lib/generated
  # Optional. Must be set to true to generate localization code that is loaded with deferred loading.
  use_deferred_loading: false # Default: false
