version: '3.3'

services:
  dart-jobs-jwt-validator-firebase:
    hostname: 'dart-jobs-jwt-validator-firebase'
    container_name: 'dart-jobs-jwt-validator-firebase'
    image: registry.plugfox.dev/dart-jobs-jwt-validator-firebase
    restart: unless-stopped
    ports:
      - '888:80'
    build:
      context: ./
      dockerfile: ./dockerfiles/jwt_validator_firebase.dockerfile
