# docker compose -f ./dart-jobs.prod.compose.yml up -d site

version: '3.9'

services:
  dart-jobs-jwt-validator-firebase:
    hostname: 'dart-jobs-jwt-validator-firebase'
    container_name: 'dart-jobs-jwt-validator-firebase'
    image: registry.plugfox.dev/dart-jobs-jwt-validator-firebase
    restart: unless-stopped
    ports:
      - '888:80'
    build:
      context: ./
      dockerfile: ./dockerfiles/jwt_validator_firebase.dockerfile

  #site:
  #  hostname: dart-jobs-site
  #  container_name: dart-jobs-site
  #  image: registry.plugfox.dev/dart-jobs-site
  #  restart: unless-stopped
  #  ports:
  #    - '80:80'
  #  build:
  #    context: ./
  #    dockerfile: dockerfiles/site.dockerfile
  #  healthcheck:
  #    test: ["CMD", "curl", "-f", "http://localhost:80"]
  #    interval: 60s
  #    timeout: 10s
  #    retries: 3
  #  deploy:
  #    replicas: 1
  #    resources:
  #      reservations:
  #        cpus: '0.10'
  #        memory: 64M
  #      limits:
  #        cpus: '0.25'
  #        memory: 256M
