# docker compose -f ./docker-compose.yml up -d dart-job-auth

version: '3.9'

services:
  dart-job-auth:
    hostname: dart-jobs-auth
    container_name: dart-job-auth
    image: registry.plugfox.dev/dart-job-auth:latest
    restart: unless-stopped
    networks:
      - internal
      - traefik-public
    #ports:
    #  - '888:80'
    #command:
    #  - dotnet JwtValidatorFirebase.dll
    #healthcheck:
    #  test: curl --fail -s http://127.0.0.1:80/healthcheck || exit 1
    #  interval: 30s
    #  timeout: 15s
    #  retries: 3
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
    build:
      context: ./
      dockerfile: ./dockerfiles/dart-job-auth.dockerfile

  #dart-jobs-site:
  #  hostname: dart-jobs-site
  #  container_name: dart-jobs-site
  #  image: registry.plugfox.dev/dart-jobs-site
  #  restart: unless-stopped
  #  ports:
  #    - '80:80'
  #  build:
  #    context: ./
  #    dockerfile: dockerfiles/site.dockerfile
  #  healthcheck:
  #    test: ["CMD", "curl", "-f", "http://localhost:80"]
  #    interval: 60s
  #    timeout: 10s
  #    retries: 3
  #  deploy:
  #    replicas: 1
  #    resources:
  #      reservations:
  #        cpus: '0.10'
  #        memory: 64M
  #      limits:
  #        cpus: '0.25'
  #        memory: 256M
