// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.g.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBst2CWEUfNuaHh9OA3XW3JdZ3vpLGPMcg',
    appId: '1:174403318860:web:d8f54a5b305667d08230e9',
    messagingSenderId: '174403318860',
    projectId: 'dart-job',
    authDomain: 'dart-job.firebaseapp.com',
    storageBucket: 'dart-job.appspot.com',
    measurementId: 'G-BYS0GKHDNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE8gu9EAmneynKOrubIZAr3sLJRRYpNNk',
    appId: '1:174403318860:android:c87ac081c37ac39a8230e9',
    messagingSenderId: '174403318860',
    projectId: 'dart-job',
    storageBucket: 'dart-job.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2U4Hy4d9x7AVo-k1LtMpH01-1ADYKeig',
    appId: '1:174403318860:ios:98002ef72b0503fc8230e9',
    messagingSenderId: '174403318860',
    projectId: 'dart-job',
    storageBucket: 'dart-job.appspot.com',
    androidClientId: '174403318860-8febsjk05jafs4u5ru5te1ilu7aiiv1b.apps.googleusercontent.com',
    iosClientId: '174403318860-gaiim23hsprlr34j16amt3evcmg1ov91.apps.googleusercontent.com',
    iosBundleId: 'dev.plugfox.dartjobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2U4Hy4d9x7AVo-k1LtMpH01-1ADYKeig',
    appId: '1:174403318860:ios:98002ef72b0503fc8230e9',
    messagingSenderId: '174403318860',
    projectId: 'dart-job',
    storageBucket: 'dart-job.appspot.com',
    androidClientId: '174403318860-8febsjk05jafs4u5ru5te1ilu7aiiv1b.apps.googleusercontent.com',
    iosClientId: '174403318860-gaiim23hsprlr34j16amt3evcmg1ov91.apps.googleusercontent.com',
    iosBundleId: 'dev.plugfox.dartjobs',
  );
}
