targets:
  $default:
    sources:
      - $package$
      - pubspec.yaml
      - schema.graphql
      - lib/**
      - test/**
      - queries/**
    builders:
      # Data classes json
      json_serializable:
        enabled: true
        generate_for:
          exclude:
            - test
          include:
            - lib/**
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
          #nullable: true
      # Data classes freezed
      freezed:
        enabled: true
        options:
          union_key: type
          union_value_case: snake
        generate_for:
          exclude:
            - test
          include:
            - lib/**
      # GraphQL Artemis
      artemis:
        options:
          schema_mapping:
            - schema: schema.graphql
              queries_glob: queries/**.graphql
              output: lib/src/graphql/api.dart
          scalar_mapping:
            - custom_parser_import: 'package:dart_jobs_shared/src/graphql/parsers/timestamp.dart'
              graphql_type: timestamp
              dart_type:
                name: DateTime
                imports:
                  - 'package:dart_jobs_shared/util.dart'
            - custom_parser_import: 'package:dart_jobs_shared/src/graphql/parsers/bpchar.dart'
              graphql_type: bpchar
              dart_type: String
            - custom_parser_import: 'package:dart_jobs_shared/src/graphql/parsers/text.dart'
              graphql_type: _text
              dart_type:
                name: List<String>
                imports:
                  - 'package:dart_jobs_shared/util.dart'
            - custom_parser_import: 'package:dart_jobs_shared/src/graphql/parsers/level.dart'
              graphql_type: level
              dart_type:
                name: DeveloperLevel
                imports:
                  - 'package:dart_jobs_shared/util.dart'
                  - 'package:dart_jobs_shared/model.dart'
            - custom_parser_import: 'package:dart_jobs_shared/src/graphql/parsers/level.dart'
              graphql_type: _level
              dart_type:
                name: List<DeveloperLevel>
                imports:
                  - 'package:dart_jobs_shared/util.dart'
                  - 'package:dart_jobs_shared/model.dart'
            - custom_parser_import: 'package:dart_jobs_shared/src/graphql/parsers/employment.dart'
              graphql_type: employment
              dart_type:
                name: Employment
                imports:
                  - 'package:dart_jobs_shared/util.dart'
                  - 'package:dart_jobs_shared/model.dart'
            - custom_parser_import: 'package:dart_jobs_shared/src/graphql/parsers/employment.dart'
              graphql_type: _employment
              dart_type:
                name: List<Employment>
                imports:
                  - 'package:dart_jobs_shared/util.dart'
                  - 'package:dart_jobs_shared/model.dart'
            - custom_parser_import: 'package:dart_jobs_shared/src/graphql/parsers/relocation.dart'
              graphql_type: relocation
              dart_type:
                name: Relocation
                imports:
                  - 'package:dart_jobs_shared/util.dart'
                  - 'package:dart_jobs_shared/model.dart'
            - custom_parser_import: 'package:dart_jobs_shared/src/graphql/parsers/int_array.dart'
              graphql_type: _int4
              dart_type:
                name: List<int>
                imports:
                  - 'package:dart_jobs_shared/util.dart'
              #dart_type:
              #  name: MultipartFile
              #  imports:
              #    - 'package:http/http.dart'
      #built_value_generator|built_value:
      #  enabled: true
      #  generate_for:
      #    exclude:
      #      - test
      #    include:
      #      - lib/**
      #build_web_compilers:entrypoint:
      #  # These are globs for the entrypoints you want to compile.
      #  generate_for:
      #    - test/**.browser_test.dart
      #    - web/**.dart
      #  enabled: true
      #  options:
      #    sound_null_safety: true
      #    compiler: dart2js
      #    # List any dart2js specific args here, or omit it.
      #    dart2js_args:
      #      - -DIS_WEB=true
      #      - -O2
      #pubspec_generator:
      #  options:
      #    output: lib/src/common/constant/pubspec.yaml.g.dart
