name: dart_jobs_shared
description: Dart Jobs - shared entities
publish_to: none
version: 0.6.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0'

dependencies:
  # Annotation & Code-generation
  meta: ^1.7.0
  json_annotation: ^4.3.0
  freezed_annotation: ^1.0.0
  equatable: ^2.0.3
  #built_value: ^8.1.3
  #built_collection: ^5.1.1

  # GraphQL
  http: ^0.13.4
  gql: ^0.13.1-alpha+1645425888336
  gql_exec: 0.3.2-alpha+1635885531651
  gql_link: 0.4.2-alpha+1635885531659
  gql_dedupe_link: 2.0.2-alpha+1635885531760
  artemis: ^7.3.2-beta
  #graphql: any
  #gql_http_link: ^0.4.0

  # Utils
  sentry: 6.3.0
  l: ^3.0.1
  #path: ^1.8.0
  #fixnum: ^1.0.0
  #money2: ^3.0.0-beta.6

dev_dependencies:
  analyzer: ">=2.8.0 <4.0.0"
  build_runner: ^2.1.4
  #built_value_generator: ^8.1.3
  json_serializable: ^6.0.1
  freezed: ^1.1.0
  lints: ^1.0.0
  test: ^1.16.0

#dependency_overrides:
  #gql_exec: 0.3.0
  #gql_link: 0.4.0
  #gql_http_link: 0.4.0
  #analyzer: ^2.7.0
  # https://github.com/gql-dart/gql/issues/289
  #gql_exec: 0.3.0